# Generated by Django 4.2.3 on 2023-08-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proucts',
            field=models.ManyToManyField(related_name='orders', to='shopapp.product'),
        ),
    ]
