# Generated by Django 4.2.3 on 2023-08-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_order_proucts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='proucts',
            new_name='products',
        ),
    ]
