# Generated by Django 4.2.3 on 2023-08-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_rename_proucts_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliveru_address',
            new_name='delivery_address',
        ),
    ]
