# Generated by Django 4.2.3 on 2023-08-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_rename_deliveru_address_order_delivery_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
